### ISSUE TITLE
Remove Tekton taskrun resource requests

### ISSUE THREAD

**Issue by yftacherzog** [konflux-ci/konflux-ci#1748]
We're facing issues both in CI and outside of CI in which tasks our pipelines are referencing include resource requests which go beyond what a local environment or a github runner can provide.

We've been working around those issues for a while now, but it might be that finding a way to ignore/remove all taskrun resource requests altogether will be a way to address it once and for all-ish.

**Comment by yftacherzog** [comment]
Potentially, if we cannot do it safely on any Tekton CR, maybe we can do the mutation on the pods created by the CR.

**Comment by yftacherzog** [comment]
After talking to the tekton team, it seems as pods is the way to go.
I was able to create a Kyverno policy to fulfill this.
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: remove-tekton-taskrun-resource-requests
spec:
  rules:
  - name: remove-resource-requests-for-tekton-taskrun-pods
    match:
      any:
      - resources:
          kinds:
          - Pod
          selector:
            matchLabels:
              app.kubernetes.io/managed-by: tekton-pipelines
    mutate:
      foreach: 
      - list: "request.object.spec.containers"
        patchesJson6902: |-
          # - op: remove
          #   path: /spec/containers/{{elementIndex}}/resources/requests
          - op: replace
            path: /spec/containers/{{elementIndex}}/resources/requests
            value:
              memory: 1
              cpu: 1m
```
This one only touches resources on the container level. Probably need to do something similar to resources on the pod level as well.

Both replace and remove work, but when we remove the requests section altogether, it seems as a default value is being applied, at least for memory, which can be quite big, so setting a very small value instead of deleting might be better.

Next, we can try installing Kyverno in our cluster (need to tweak the default roles to allow it to touch pods) and create a similar policy, and see if it allows the PR of the ec-task to pass.

cc @psturc @gbenhaim
