### ISSUE TITLE
keycloak operator - Startup probe failed: Get "http://10.244.0.52:8080/q/health/started": dial tcp 10.244.0.52:8080: connect: connection refused

### ISSUE THREAD

**Issue by cmoulliard** [konflux-ci/konflux-ci#591]
## Issue

When we install konflux using podman on macos where a VM is created using AppleHV, then there is an issue as kubernetes cannot probe the keycloak operator endpoint

```
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  7m33s                  default-scheduler  Successfully assigned keycloak/keycloak-operator-6d5c7bb879-w5shv to konflux-control-plane
  Normal   Pulled     7m32s                  kubelet            Successfully pulled image "quay.io/keycloak/keycloak-operator:24.0.2" in 477ms (477ms including waiting). Image size: 203173701 bytes.
  Normal   Pulled     7m                     kubelet            Successfully pulled image "quay.io/keycloak/keycloak-operator:24.0.2" in 967ms (967ms including waiting). Image size: 203173701 bytes.
  Normal   Created    6m24s (x3 over 7m32s)  kubelet            Created container keycloak-operator
  Normal   Started    6m24s (x3 over 7m32s)  kubelet            Started container keycloak-operator
  Normal   Pulled     6m24s                  kubelet            Successfully pulled image "quay.io/keycloak/keycloak-operator:24.0.2" in 1.282s (1.282s including waiting). Image size: 203173701 bytes.
  Warning  Unhealthy  5m53s (x9 over 7m23s)  kubelet            Startup probe failed: Get "http://10.244.0.52:8080/q/health/started": dial tcp 10.244.0.52:8080: connect: connection refused
  Normal   Killing    5m53s (x3 over 7m3s)   kubelet            Container keycloak-operator failed startup probe, will be restarted
  Normal   Pulling    5m51s (x4 over 7m33s)  kubelet            Pulling image "quay.io/keycloak/keycloak-operator:24.0.2"
  Warning  BackOff    2m13s (x6 over 4m41s)  kubelet            Back-off restarting failed container keycloak-operator in pod keycloak-operator-6d5c7bb879-w5shv_keycloak(6cd03e69-8052-4831-aa64-d8f496a48a48)
```

This issue which is similar to mine has been discussed here: https://github.com/keycloak/keycloak/issues/30355

If we install the version `25.0.6` of keycloak operator, then the error disappears

@gbenhaim

**Comment by calebevans** [comment]
I am also encountering this issue and have yet to find a solution in my case. I have listed some notes below, if I figure out a solution I will report back.

**What I have Tried**
- Update keycloak to version `25.0.6` per the issue description.
- Update keycloak to version `26.0.4` (released today).
- Increase kind cluster resources:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        system-reserved: memory=12Gi,cpu=8
  extraPortMappings:
  - containerPort: 30010
    hostPort: 8888
    protocol: TCP
  - containerPort: 30011
    hostPort: 9443
    protocol: TCP
```

**System Information**
OS: Fedora 40
Docker Version: 27.3.1
Kind version: 0.24.0
